import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import { TopNav } from "@/widgets/TopNav";
import { Navbar } from "@/widgets/Navbar";
import { Footer } from "@/widgets/Footer";

import { Providers } from "./providers";
import { AuthInit } from "@/components/AuthInit";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <Providers>
          <AuthInit />
          <TopNav />
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
