import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { TopNav } from "@/widgets/TopNav";
import { Navbar } from "@/widgets/Navbar";
import { Footer } from "@/widgets/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TopNav />
      <Navbar />
      <body className={`${montserrat.variable}  antialiased`}>{children}</body>
      <Footer />
    </html>
  );
}
